---
version: '3'
services:
  syncthing1:
    image: "${USERNAME}/${IMAGE}-nanoserver:${VERSION}"
    build:
      context: .

  syncthing2:
    image: "${USERNAME}/${IMAGE}-windowsservercore:${VERSION}"
    build:
      context: Dockerfile.windowsservercore